### ISSUE TITLE
127.0.0.1 refused to connect error

### ISSUE THREAD

**Issue by Blade694** [slatinsky/DiscordChatExporter-frontend#3]
whenever i try to open the start_viewer.bat it shows that 127.0.0.1 error in a browser window and 
C:\Users\xyz\Downloads\DiscordChatExporter-frontend-v1.8.1-win\bin>if exist "C:\Program Files\Google\Chrome\Application\chrome.exe" ("C:\Program Files\Google\Chrome\Application\chrome.exe" --app="http://127.0.0.1:21011/index.html" --enable-precise-memory-info )  else (rundll32 url.dll,FileProtocolHandler http://127.0.0.1:21011/index.html )
this error. help???

**Comment by slatinsky** [comment]
Hello,

thanks for reporting an issue.
The message you saw just means "If Chrome is installed, open it in Chrome in app mode, else open in default browser", it's not an error.

I fixed this race condition (browser opened before server is started) in the latest release [v1.8.2](https://github.com/slatinsky/DiscordChatExporter-frontend/releases/tag/v1.8.2). It should fix your issue.

**Comment by Blade694** [comment]
Thank you, the problem is fixed now. :)

**Comment by evangelos-ch** [comment]
Still happens for me on both the latest release and the latest beta build, am I missing something?
![image](https://user-images.githubusercontent.com/11058975/228984951-2f490071-e667-4054-ae26-06c9125d6950.png)

Same thing when trying to access 127.0.0.1:21011 (or the localhost equivalent) in my actual browser (Firefox).

**Comment by slatinsky** [comment]
Please check out top of `dcef/logs.txt` if all required ports are available.

**Comment by evangelos-ch** [comment]
They are, full log:

```
2023-03-31 12:28:21.123080  windows-runner: started primary instance
2023-03-31 12:28:21.127079  windows-runner: used ports: 135 139 445 902 912 2222 5040 5354 7680 9010 9080 9100 9180 9614 27015 27036 27060 45654 49664 49665 49666 49667 49668 49695 49756 65001
2023-03-31 12:28:21.127079  windows-runner: OK: All required ports are available.
2023-03-31 12:28:21.128079  windows-runner: nginx started
2023-03-31 12:28:21.135678  windows-runner: nginx finished
2023-03-31 12:28:22.128775  windows-runner: mongodb started
2023-03-31 12:28:22.128775  windows-runner: http-server started
2023-03-31 12:28:22.129781  windows-runner: fastapi started
2023-03-31 12:28:22.129781  windows-runner: preprocess started
2023-03-31 12:28:22.137780  windows-runner: mongodb finished
2023-03-31 12:28:22.137780  windows-runner: http-server finished
2023-03-31 12:28:22.137780  windows-runner: fastapi finished
2023-03-31 12:28:22.137780  windows-runner: preprocess finished
2023-03-31 12:28:22.138781  windows-runner: creating window
```

**Comment by slatinsky** [comment]
Sorry, I can't reproduce it.

Docker version should run on Windows too if you use WSL2.

**Comment by WanHaes** [comment]
> Still happens for me on both the latest release and the latest beta build, am I missing something? ![image](https://user-images.githubusercontent.com/11058975/228984951-2f490071-e667-4054-ae26-06c9125d6950.png)
> 
> Same thing when trying to access 127.0.0.1:21011 (or the localhost equivalent) in my actual browser (Firefox).

This happens if there are cyrillic characters and/or some unusual unicode characters in the path to the program folder. It seems that the problem is caused by nginx, here's their error logs:
```
2024/04/05 04:53:37 [emerg] 8684#15324: CreateFile() "D:\CORE\Тест\DiscordChatExporter-frontend 2.9.0\dcef\backend\nginx/conf/nginx-prod.conf" failed (1113: No mapping for the Unicode character exists in the target multi-byte code page)
2024/04/05 05:01:18 [emerg] 13012#6316: CreateFile() "D:\CORE\? Test\DiscordChatExporter-frontend 2.9.0\dcef\backend\nginx/conf/nginx-prod.conf" failed (123: The filename, directory name, or volume label syntax is incorrect)
```
